package cn.edu.xidian.iii.domain;

// Generated 2015-11-12 11:21:44 by Hibernate Tools 3.4.0.CR1

/**
 * Configtable generated by hbm2java
 */
public class Configtable implements java.io.Serializable {

	private ConfigtableId id;

	public Configtable() {
	}

	public Configtable(ConfigtableId id) {
		this.id = id;
	}

	public ConfigtableId getId() {
		return this.id;
	}

	public void setId(ConfigtableId id) {
		this.id = id;
	}

}
