package cn.edu.xidian.iii.domain;

// Generated 2015-11-12 11:21:44 by Hibernate Tools 3.4.0.CR1

/**
 * CoursedeviceId generated by hbm2java
 */
public class CoursedeviceId implements java.io.Serializable {

	private Integer courseId;
	private String deviceType;

	public CoursedeviceId() {
	}

	public CoursedeviceId(Integer courseId, String deviceType) {
		this.courseId = courseId;
		this.deviceType = deviceType;
	}

	public Integer getCourseId() {
		return this.courseId;
	}

	public void setCourseId(Integer courseId) {
		this.courseId = courseId;
	}

	public String getDeviceType() {
		return this.deviceType;
	}

	public void setDeviceType(String deviceType) {
		this.deviceType = deviceType;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CoursedeviceId))
			return false;
		CoursedeviceId castOther = (CoursedeviceId) other;

		return (this.getCourseId() == castOther.getCourseId())
				&& ((this.getDeviceType() == castOther.getDeviceType()) || (this
						.getDeviceType() != null
						&& castOther.getDeviceType() != null && this
						.getDeviceType().equals(castOther.getDeviceType())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCourseId();
		result = 37
				* result
				+ (getDeviceType() == null ? 0 : this.getDeviceType()
						.hashCode());
		return result;
	}

}
