package cn.edu.xidian.iii.domain;

// Generated 2015-11-12 11:21:44 by Hibernate Tools 3.4.0.CR1

/**
 * Elective generated by hbm2java
 */
public class Elective implements java.io.Serializable {

	private ElectiveId id;
	private User user;
	private Course course;
	private Integer score;
	private Integer count;
	private Integer totalTime;

	public Elective() {
	}

	public Elective(ElectiveId id, User user, Course course) {
		this.id = id;
		this.user = user;
		this.course = course;
	}

	public Elective(ElectiveId id, User user, Course course, Integer score,
			Integer count, Integer totalTime) {
		this.id = id;
		this.user = user;
		this.course = course;
		this.score = score;
		this.count = count;
		this.totalTime = totalTime;
	}

	public ElectiveId getId() {
		return this.id;
	}

	public void setId(ElectiveId id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public Integer getScore() {
		return this.score;
	}

	public void setScore(Integer score) {
		this.score = score;
	}

	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

	public Integer getTotalTime() {
		return this.totalTime;
	}

	public void setTotalTime(Integer totalTime) {
		this.totalTime = totalTime;
	}

}
