package cn.edu.xidian.iii.domain;

// Generated 2015-11-12 11:21:44 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer userId;
	private String userName;
	private String role;
	private Integer cardcode;
	private String password;
	private Date registerTime;
	private String email;
	private String phone;
	private String studentNum;
	private Set<Elective> electives = new HashSet<Elective>(0);
	private Set<Teaming> teamings = new HashSet<Teaming>(0);
	private Set<Team> teams = new HashSet<Team>(0);

	public User() {
	}

	public User(String userName, String role, Integer cardcode, String password,
			String email, String phone, String studentNum) {
		this.userName = userName;
		this.role = role;
		this.cardcode = cardcode;
		this.password = password;
		this.email = email;
		this.phone = phone;
		this.studentNum = studentNum;
	}

	public User(String userName, String role, Integer cardcode, String password,
			Date registerTime, String email, String phone, String studentNum,
			Set<Elective> electives, Set<Teaming> teamings, Set<Team> teams) {
		this.userName = userName;
		this.role = role;
		this.cardcode = cardcode;
		this.password = password;
		this.registerTime = registerTime;
		this.email = email;
		this.phone = phone;
		this.studentNum = studentNum;
		this.electives = electives;
		this.teamings = teamings;
		this.teams = teams;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public Integer getCardcode() {
		return this.cardcode;
	}

	public void setCardcode(Integer cardcode) {
		this.cardcode = cardcode;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getRegisterTime() {
		return this.registerTime;
	}

	public void setRegisterTime(Date registerTime) {
		this.registerTime = registerTime;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getStudentNum() {
		return this.studentNum;
	}

	public void setStudentNum(String studentNum) {
		this.studentNum = studentNum;
	}

	public Set<Elective> getElectives() {
		return this.electives;
	}

	public void setElectives(Set<Elective> electives) {
		this.electives = electives;
	}

	public Set<Teaming> getTeamings() {
		return this.teamings;
	}

	public void setTeamings(Set<Teaming> teamings) {
		this.teamings = teamings;
	}

	public Set<Team> getTeams() {
		return this.teams;
	}

	public void setTeams(Set<Team> teams) {
		this.teams = teams;
	}

}
