package cn.edu.xidian.iii.domain;

// Generated 2015-11-12 11:21:44 by Hibernate Tools 3.4.0.CR1

/**
 * ConfigtableId generated by hbm2java
 */
public class ConfigtableId implements java.io.Serializable {

	private String configType;
	private String configKey;
	private String configValue;

	public ConfigtableId() {
	}

	public ConfigtableId(String configType, String configKey, String configValue) {
		this.configType = configType;
		this.configKey = configKey;
		this.configValue = configValue;
	}

	public String getConfigType() {
		return this.configType;
	}

	public void setConfigType(String configType) {
		this.configType = configType;
	}

	public String getConfigKey() {
		return this.configKey;
	}

	public void setConfigKey(String configKey) {
		this.configKey = configKey;
	}

	public String getConfigValue() {
		return this.configValue;
	}

	public void setConfigValue(String configValue) {
		this.configValue = configValue;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ConfigtableId))
			return false;
		ConfigtableId castOther = (ConfigtableId) other;

		return ((this.getConfigType() == castOther.getConfigType()) || (this
				.getConfigType() != null && castOther.getConfigType() != null && this
				.getConfigType().equals(castOther.getConfigType())))
				&& ((this.getConfigKey() == castOther.getConfigKey()) || (this
						.getConfigKey() != null
						&& castOther.getConfigKey() != null && this
						.getConfigKey().equals(castOther.getConfigKey())))
				&& ((this.getConfigValue() == castOther.getConfigValue()) || (this
						.getConfigValue() != null
						&& castOther.getConfigValue() != null && this
						.getConfigValue().equals(castOther.getConfigValue())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getConfigType() == null ? 0 : this.getConfigType()
						.hashCode());
		result = 37 * result
				+ (getConfigKey() == null ? 0 : this.getConfigKey().hashCode());
		result = 37
				* result
				+ (getConfigValue() == null ? 0 : this.getConfigValue()
						.hashCode());
		return result;
	}

}
