package cn.edu.xidian.iii.domain;

// Generated 2015-11-12 11:21:44 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Course generated by hbm2java
 */
public class Course implements java.io.Serializable {

	private Integer courseId;
	private String courseName;
	private String teacher;
	private String tphone;
	private String classroom;
	private Date beginTime;
	private Date endTime;
	private Integer maxNumber;
	private String identifier;
	private Set<Elective> electives = new HashSet<Elective>(0);
	private Set<Team> teams = new HashSet<Team>(0);
	private Set<Coursedevice> coursedevices = new HashSet<Coursedevice>(0);

	public Course() {
	}

	public Course(String courseName, String teacher, String tphone,
			String classroom, String identifier) {
		this.courseName = courseName;
		this.teacher = teacher;
		this.tphone = tphone;
		this.classroom = classroom;
		this.identifier = identifier;
	}

	public Course(String courseName, String teacher, String tphone,
			String classroom, Date beginTime, Date endTime, Integer maxNumber,
			String identifier, Set<Elective> electives, Set<Team> teams,
			Set<Coursedevice> coursedevices) {
		this.courseName = courseName;
		this.teacher = teacher;
		this.tphone = tphone;
		this.classroom = classroom;
		this.beginTime = beginTime;
		this.endTime = endTime;
		this.maxNumber = maxNumber;
		this.identifier = identifier;
		this.electives = electives;
		this.teams = teams;
		this.coursedevices = coursedevices;
	}

	public Integer getCourseId() {
		return this.courseId;
	}

	public void setCourseId(Integer courseId) {
		this.courseId = courseId;
	}

	public String getCourseName() {
		return this.courseName;
	}

	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	public String getTeacher() {
		return this.teacher;
	}

	public void setTeacher(String teacher) {
		this.teacher = teacher;
	}

	public String getTphone() {
		return this.tphone;
	}

	public void setTphone(String tphone) {
		this.tphone = tphone;
	}

	public String getClassroom() {
		return this.classroom;
	}

	public void setClassroom(String classroom) {
		this.classroom = classroom;
	}

	public Date getBeginTime() {
		return this.beginTime;
	}

	public void setBeginTime(Date beginTime) {
		this.beginTime = beginTime;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public Integer getMaxNumber() {
		return this.maxNumber;
	}

	public void setMaxNumber(Integer maxNumber) {
		this.maxNumber = maxNumber;
	}

	public String getIdentifier() {
		return this.identifier;
	}

	public void setIdentifier(String identifier) {
		this.identifier = identifier;
	}

	public Set<Elective> getElectives() {
		return this.electives;
	}

	public void setElectives(Set<Elective> electives) {
		this.electives = electives;
	}

	public Set<Team> getTeams() {
		return this.teams;
	}

	public void setTeams(Set<Team> teams) {
		this.teams = teams;
	}

	public Set<Coursedevice> getCoursedevices() {
		return this.coursedevices;
	}

	public void setCoursedevices(Set<Coursedevice> coursedevices) {
		this.coursedevices = coursedevices;
	}

}
