package cn.edu.xidian.iii.domain;

// Generated 2015-11-12 11:21:44 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Devicetype generated by hbm2java
 */
public class Devicetype implements java.io.Serializable {

	private String deviceType;
	private Integer total;
	private Integer inventory;
	private Set<Coursedevice> coursedevices = new HashSet<Coursedevice>(0);
	private Set<Appointment> appointments = new HashSet<Appointment>(0);
	private Set<Device> devices = new HashSet<Device>(0);

	public Devicetype() {
	}

	public Devicetype(String deviceType) {
		this.deviceType = deviceType;
	}

	public Devicetype(String deviceType, Integer total, Integer inventory) {
		this.deviceType = deviceType;
		this.total = total;
		this.inventory = inventory;
	}

	public Devicetype(String deviceType, Integer total, Integer inventory,
			Set<Coursedevice> coursedevices, Set<Appointment> appointments,
			Set<Device> devices) {
		this.deviceType = deviceType;
		this.total = total;
		this.inventory = inventory;
		this.coursedevices = coursedevices;
		this.appointments = appointments;
		this.devices = devices;
	}

	public String getDeviceType() {
		return this.deviceType;
	}

	public void setDeviceType(String deviceType) {
		this.deviceType = deviceType;
	}

	public Integer getTotal() {
		return this.total;
	}

	public void setTotal(Integer total) {
		this.total = total;
	}

	public Integer getInventory() {
		return this.inventory;
	}

	public void setInventory(Integer inventory) {
		this.inventory = inventory;
	}

	public Set<Coursedevice> getCoursedevices() {
		return this.coursedevices;
	}

	public void setCoursedevices(Set<Coursedevice> coursedevices) {
		this.coursedevices = coursedevices;
	}

	public Set<Appointment> getAppointments() {
		return this.appointments;
	}

	public void setAppointments(Set<Appointment> appointments) {
		this.appointments = appointments;
	}

	public Set<Device> getDevices() {
		return this.devices;
	}

	public void setDevices(Set<Device> devices) {
		this.devices = devices;
	}

}
