package cn.edu.xidian.iii.domain;

// Generated 2015-11-12 11:21:44 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Note generated by hbm2java
 */
public class Note implements java.io.Serializable {

	private Integer noteId;
	private Team team;
	private Device device;
	private Date outTime;
	private Date inTime;
	private String remark;

	public Note() {
	}

	public Note(Team team, Device device) {
		this.team = team;
		this.device = device;
	}

	public Note(Team team, Device device, Date outTime, Date inTime,
			String remark) {
		this.team = team;
		this.device = device;
		this.outTime = outTime;
		this.inTime = inTime;
		this.remark = remark;
	}

	public Integer getNoteId() {
		return this.noteId;
	}

	public void setNoteId(Integer noteId) {
		this.noteId = noteId;
	}

	public Team getTeam() {
		return this.team;
	}

	public void setTeam(Team team) {
		this.team = team;
	}

	public Device getDevice() {
		return this.device;
	}

	public void setDevice(Device device) {
		this.device = device;
	}

	public Date getOutTime() {
		return this.outTime;
	}

	public void setOutTime(Date outTime) {
		this.outTime = outTime;
	}

	public Date getInTime() {
		return this.inTime;
	}

	public void setInTime(Date inTime) {
		this.inTime = inTime;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
