package cn.edu.xidian.iii.domain;

// Generated 2015-11-12 11:21:44 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Team generated by hbm2java
 */
public class Team implements java.io.Serializable {

	private Integer teamId;
	private User user;
	private Course course;
	private Integer CTeamid;
	private Integer count;
	private Integer totalTime;
	private Set<Teaming> teamings = new HashSet<Teaming>(0);
	private Set<Note> notes = new HashSet<Note>(0);
	private Set<Appointment> appointments = new HashSet<Appointment>(0);

	public Team() {
	}

	public Team( Course course, Integer CTeamid,Integer count) {
		this.course = course;
		this.CTeamid = CTeamid;
		this.count=count;
	}
	public Team( Course course, Integer CTeamid) {
		this.course = course;
		this.CTeamid = CTeamid;
	}

	public Team(User user, Course course, Integer CTeamid, Integer count,
			Integer totalTime, Set<Teaming> teamings, Set<Note> notes,
			Set<Appointment> appointments) {
		//this.user = user;
		this.course = course;
		this.CTeamid = CTeamid;
		this.count = count;
		this.totalTime = totalTime;
		this.teamings = teamings;
		this.notes = notes;
		this.appointments = appointments;
	}

	public Integer getTeamId() {
		return this.teamId;
	}

	public void setTeamId(Integer teamId) {
		this.teamId = teamId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public Integer getCTeamid() {
		return this.CTeamid;
	}

	public void setCTeamid(Integer CTeamid) {
		this.CTeamid = CTeamid;
	}

	public Integer getCount() {
		return this.count;
	}

	
	public void setCount(Integer count) {
		this.count = count;
	}

	public Integer getTotalTime() {
		return this.totalTime;
	}

	public void setTotalTime(Integer totalTime) {
		this.totalTime = totalTime;
	}

	public Set<Teaming> getTeamings() {
		return this.teamings;
	}

	public void setTeamings(Set<Teaming> teamings) {
		this.teamings = teamings;
	}

	public Set<Note> getNotes() {
		return this.notes;
	}

	public void setNotes(Set<Note> notes) {
		this.notes = notes;
	}

	public Set<Appointment> getAppointments() {
		return this.appointments;
	}

	public void setAppointments(Set<Appointment> appointments) {
		this.appointments = appointments;
	}

}
